export const cities = [
  "New York",
  "Toronto",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Philadelphia",
  "Phoenix",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "San Francisco",
  "Indianapolis",
  "Columbus",
  "Fort Worth",
  "Charlotte",
  "Seattle",
  "Denver",
  "El Paso",
  "Detroit",
  "Washington",
  "Boston",
  "Memphis",
  "Nashville",
  "Portland",
  "Oklahoma City",
  "Las Vegas",
  "Baltimore",
  "Louisville",
  "Milwaukee",
  "Albuquerque",
  "Tucson",
  "Fresno",
  "Sacramento",
  "Kansas City",
  "Long Beach",
  "Mesa",
  "Atlanta",
  "Colorado Springs",
  "Virginia Beach",
  "Raleigh",
  "Omaha",
  "Miami",
  "Oakland",
  "Minneapolis",
  "Tulsa",
  "Wichita",
  "New Orleans",
  "Singapore",
  "Ah Soo Garden",
  "Alexandra",
  "Alexandra Estate",
  "Ama Keng",
  "Ama Keng Village",
  "Ang Mo Kio",
  "Ang Mo Kio New Town",
  "Ang Mo Kio Village",
  "Ardmore Flats",
  "Ayer Rajah",
  "Ayer Raja New Town",
  "Bajau Estate",
  "Bamboo Grove Park",
  "Bandar Baharu Jurong",
  "Ban Guan Park",
  "Banta Tengeh",
  "Adam Park",
  "Bedok Garden",
  "Bedok New Town",
  "Bedok Village",
  "Bedok Ville",
  "Bena Park",
  "Bin Tong Park",
  "Bishan New Town",
  "Boon Lay",
  "Boon Lay Resettlement Area",
  "Braddell Heights Estate",
  "Brickworks Estate",
  "Bright Hill Crescent",
  "Brizay Park",
  "Bukit Batok",
  "Bukit Batok New Town",
  "Bukit Ho Swee Estate",
  "Bedok",
  "Montreal",
  "Calgary",
  "Ottawa",
  "Edmonton",
  "Mississauga",
  "Winnipeg",
  "Vancouver",
  "Brampton",
  "Hamilton",
  "Quebec City",
  "Surrey",
  "Laval",
  "Halifax",
  "London",
  "Markham",
  "Vaughan",
  "Gatineau",
  "Saskatoon",
  "Longueuil",
  "Kitchener",
  "Burnaby",
  "Windsor",
  "Regina",
  "Richmond",
  "Richmond Hill",
  "Oakville",
  "Burlington",
  "Greater Sudbury",
  "Sherbrooke",
  "Oshawa",
  "Saguenay",
  "Lévis",
  "Barrie",
  "Abbotsford",
  "Coquitlam",
  "Trois-Rivières",
  "St. Catharines",
  "Guelph",
  "Cambridge",
  "Whitby",
  "Kelowna",
  "Kingston",
  "Ajax",
  "Langley",
  "Saanich",
  "Terrebonne",
  "Milton",
  "St. John's",
  "Thunder Bay",
  "Waterloo",
  "Delta",
  "Chatham-Kent",
  "Red Deer",
  "Strathcona County",
  "Brantford",
  "Saint-Jean-sur-Richelieu",
  "Cape Breton",
  "Lethbridge",
  "Clarington",
  "Pickering",
  "Nanaimo",
  "Kamloops",
  "Niagara Falls",
  "Victoria",
  "Brossard",
  "Repentigny",
  "Newmarket",
  "Chilliwack",
  "Maple Ridge",
  "Peterborough",
  "Kawartha Lakes",
  "Drummondville",
  "Saint-Jérôme",
  "Prince George",
  "Sault Ste. Marie",
  "MonctonNew",
  "Sarnia",
  "Wood Buffalo",
  "New Westminster",
  "Saint JohnNew",
  "Caledon",
  "Granby",
  "St. Albert",
  "Norfolk County",
  "Medicine Hat",
  "Grande Prairie",
  "Airdrie",
  "Halton Hills",
  "Port Coquitlam",
  "FrederictonNew",
  "Blainville",
  "Saint-Hyacinthe",
  "Aurora",
  "North Vancouver",
  "Welland",
  "North Bay",
  "Belleville",
  "Mirabel",
  "Hong Kong",
];
