import { Order } from "@prisma/client";
import { unstable_getServerSession } from "next-auth";
import Head from "next/head";
import prisma from "../../../../constants/prisma";
import { authOptions } from "../../../../pages/api/auth/[...nextauth]";

export default async function Page({
  params,
}: {
  params: { orderId: string; };
}) {
  const session = await unstable_getServerSession(authOptions);
  if (session == null) {
    //TODO: redirect to login
    return <div>Not logged in</div>;
  }

  const { orderId } = params;

  const order: Order | null = await prisma.order.findUnique({
    where: {
      id: orderId ?? "",
    },
  });

  if (order == null) {
    return (
      <div className="w-full h-screen bg-black flex overflow-hidden">
        <Head>
          <title>Order Not Found</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="text-xl text-white flex items-center">
          <h1 className="mx-auto">This order does not exist</h1>
        </main>
      </div>
    );
  }

  return (
    <div className="h-screen bg-black flex overflow-hidden">
      <Head>
        <title>Find your perfect setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col container mx-auto my-auto items-center py-4 text-white">
        <h1>{`Order: ${order.id}`}</h1>
        <div>{`Order was placed on ${order.createdAt}`}</div>
        <div>{`Order status is ${order.status.toLowerCase()}`}</div>
        <div>{`Order amount was \$${order.amount}`}</div>
      </main>
    </div>
  );
};