import { Order } from "@prisma/client";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import prisma from "../../../constants/prisma";

type OrderProps = {
  order: Order | undefined;
  error: string;
};

const OrderPage: NextPage<OrderProps> = ({ order, error }: OrderProps) => {
  if (order == null) {
    console.log(error);
    return (
      <div className="w-full h-screen bg-black flex overflow-hidden">
        <Head>
          <title>Order Not Found</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="text-xl text-white flex items-center">
          <h1 className="mx-auto">This order does not exist</h1>
        </main>
      </div>
    );
  }

  return (
    <div className="w-screen h-screen bg-black flex overflow-hidden">
      <Head>
        <title>Find your perfect setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col container mx-auto my-auto items-center py-4 text-white">
        <h1>{`Order: ${order.id}`}</h1>
        <div>{`Order was placed on ${order.createdAt}`}</div>
        <div>{`Order status is ${order.status.toLowerCase()}`}</div>
        <div>{`Order amount was ${order.amount}`}</div>
        <div>{`Order was for ${order.skuId}`}</div>
        <div>{`Order was sent to ${order.locationId}`}</div>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { orderId } = context.query;
  let error = "";
  if (typeof orderId == "string") {
    const order = await prisma.order
      .findUnique({
        where: {
          id: "cl5rbdfwz0039o60osoiaedgo",
        },
      })
      .catch((e) => {
        error = e;
        console.log(e);
      });
    return {
      props: {
        order: JSON.parse(JSON.stringify(order ?? null)),
        error: JSON.stringify(error),
      },
    };
  }
  return { props: {} };
};
// export const getServerSideProps: GetServerSideProps = async (context) => {
//   const { orderId } = context.query;
//   const session = await unstable_getServerSession(
//     context.req,
//     context.res,
//     authOptions
//   );
//   if (session && typeof orderId == "string") {
//     const user = await prisma.user.findUnique({
//       where: {
//         email: session?.user?.email ?? "",
//       },
//     });
//     console.log(user);
//     const order = await prisma.order.findUnique({
//       where: {
//         id: orderId,
//       },
//     });
//     return {
//       props: {
//         order: JSON.parse(
//           JSON.stringify(order?.companyId == user?.companyId ? order : null)
//         ),
//       },
//     };
//   }
//   return { props: {} };
// };

export default OrderPage;
