import { Elements } from "@stripe/react-stripe-js";
import { Appearance, loadStripe } from "@stripe/stripe-js";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import CheckoutForm from "../../components/form/checkout-form";
import ReLogo from "../../components/form/re-logo";
import { useFormState } from "../../context/form-context";

const stripePromise = loadStripe(
  process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY ?? ""
);

const Checkout: NextPage = () => {
  const [clientSecret, setClientSecret] = useState("");
  const { calculateTotal, cart, locations } = useFormState();
  const total = calculateTotal();

  useEffect(() => {
    fetch("/api/payment-intent", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ cost: total }),
    })
      .then((res) => res.json())
      .then((data) => setClientSecret(data.clientSecret));
  }, [total]);

  const appearance: Appearance = {
    theme: "night",
    variables: {
      colorPrimary: "#58FEC4",
    },
  };

  const options = {
    clientSecret,
    appearance,
  };

  let items = [];
  for (let city in cart) {
    if (locations.length > 1) {
      items.push(
        <div>
          <div>{`${city} orders`}</div>
        </div>
      );
    }
    items.push(
      cart[city].map((sku) => (
        <div
          className="flex columns-2 justify-between items-center mr-4 mt-5 mb-8"
          key={sku.title}
        >
          <div className="flex columns-2 justify-start items-center">
            <div className="h-12 w-12 overflow-hidden rounded place-content-center mr-3">
              <Image
                src={sku.image}
                alt={"takeout front"}
                height={"100%"}
                width={"100%"}
              />
            </div>
            <div>
              <div className="text-sm font-semibold mb-0.5">{sku.title}</div>
              <div className="text-xs text-gray-300">{`Qty ${sku.quantity}`}</div>
            </div>
          </div>
          <div>
            <div className="text-sm font-semibold mb-0.5">{`$${(
              sku.price * parseInt(sku.quantity)
            ).toFixed(2)}`}</div>
            <div className="text-xs text-gray-300">{sku.priceString}</div>
          </div>
        </div>
      ))
    );
    items.push(
      <div className="flex columns-2 pl-16 justify-between mr-6 mb-8">
        <div className="">
          <div className="text-sm font-semibold mb-0.5">Shipping</div>
          <div className="text-xs text-gray-300">{`Taiwan to ${city} 5-7 days`}</div>
        </div>
        <div className="">
          <div className="text-sm font-semibold mb-0.5">Calculated later</div>
        </div>
      </div>
    );
  }

  return (
    <div className="w-screen h-screen bg-black flex items-center justify-center text-white">
      <Head>
        <title>Find your perfect setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReLogo />

      <main className="flex p-6 columns-2 mx-20 my-1 h-screen">
        <div className="flex-column items-start w-1/2 h-full overflow-auto mr-4">
          <h2 className="text-lg">Pay Re Company</h2>
          <h1 className=" text-4xl font-semibold pb-4">{`$${total.toFixed(
            2
          )}`}</h1>
          {items}
          <div className="ml-16 mr-6 border my-4" />
          <div className="flex columns-2 pl-16 justify-between mr-6 mb-4 text-gray-300">
            <div className="">
              <div className="text-sm font-semibold mb-0.5">Tax (7%)</div>
            </div>
            <div className="">
              <div className="text-sm font-semibold mb-0.5">{`$${(
                total * 0.7
              ).toFixed(2)}`}</div>
            </div>
          </div>
          <div className="flex columns-2 pl-16 justify-between mr-6 mb-8">
            <div className="">
              <div className="text-sm font-semibold mb-0.5">Total due</div>
            </div>
            <div className="">
              <div className="text-sm font-semibold mb-0.5">{`$${(
                total * 1.07
              ).toFixed(2)}`}</div>
            </div>
          </div>
        </div>
        <div className="w-1/2 h-full">
          {clientSecret && (
            // eslint-disable-next-line
            <Elements options={options} stripe={stripePromise}>
              <CheckoutForm />
            </Elements>
          )}
        </div>
      </main>
    </div>
  );
};

export default Checkout;
