import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import FormNextButton from "../../components/form/next-button";
import FormOptionButton from "../../components/form/option-button";
import { useAppContext } from "../../context/context-provider";
import { Product, SKU } from "../../models/products";
import styles from "../../styles/Form.module.css";

const re_container: Product = new Product(
  "Re Container",
  ["16 oz", "32 oz"],
  ["Polypropylene", "Recyled Polypropylene", "Bio Based"],
  "/images/takeout_vent.png"
);

const ProductPage: NextPage = () => {
  const [chosenSizes, setChosenSizes] = useState<string[]>([]);
  const [chosenMaterial, setChosenMaterial] = useState<string>("");
  const [context, updateAppContext] = useAppContext();

  function handleClick(optionLabel: string) {
    console.log(optionLabel);
    console.log(re_container.sizes);
    if (re_container.sizes.includes(optionLabel)) {
      console.log("SIZE");
      if (chosenSizes.includes(optionLabel)) {
        setChosenSizes(chosenSizes.filter((val) => val != optionLabel));
      } else {
        setChosenSizes([...chosenSizes, optionLabel]);
      }
    } else {
      if (optionLabel == chosenMaterial) {
        setChosenMaterial("");
      } else {
        setChosenMaterial(optionLabel);
      }
    }
  }

  function handleChange(quantity: string, sku: string) {
    let changedSKU = re_container.sku.get(sku) ?? new SKU("", "", "");
    changedSKU.quantity = quantity;
    context.addToCart(changedSKU);
    console.log(`cart`);
    console.log(context);
    updateAppContext(context);
  }

  const sizes = re_container.sizes.map((size) => (
    <li className={styles.listItem} key={size}>
      <FormOptionButton
        handleClick={() => handleClick(size)}
        label={size}
        selected={chosenSizes.includes(size)}
      />
    </li>
  ));

  const materials = re_container.materials.map((material) => (
    <li className={styles.listItem} key={material}>
      <FormOptionButton
        handleClick={() => handleClick(material)}
        label={material}
        selected={material == chosenMaterial}
      />
    </li>
  ));

  const skus = chosenSizes
    .sort((a, b) => parseInt(a.split(" ")[0]) - parseInt(b.split(" ")[0]))
    .map((size, index) => (
      <li className={styles.listItem} key={index}>
        <div className={styles.quantityTitle}>
          {size + " " + chosenMaterial}
        </div>
        <input
          type="text"
          className={styles.quantityInput}
          onChange={(e) =>
            handleChange(
              e.target.value,
              index.toString() +
                re_container.materials.indexOf(chosenMaterial).toString()
            )
          }
        />
      </li>
    ));

  return (
    <div className={styles.container}>
      <Head>
        <title>Find your perfect setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.row}>
          <div className={styles.pictureColumn}>
            <Image
              src={re_container.image}
              width={500}
              height={500}
              alt={re_container.title}
            />
          </div>
          <div id="options" className={styles.column}>
            <h1 className={styles.productTitle}>{re_container.title}</h1>
            <div
              style={{
                border: "2px solid transparent",
              }}
            >
              <h2 className={styles.optionHeader}>Choose your size(s)</h2>
              <ul className={styles.grid}>{sizes}</ul>
            </div>
            <div>
              <h2 className={styles.optionHeader}>Choose your material</h2>
              <ul className={styles.grid}>{materials}</ul>
            </div>
            {chosenSizes.length > 0 && chosenMaterial.length > 0 && (
              <div>
                <div>
                  <h2 className={styles.optionHeader}>Choose your quanity</h2>
                  <ul className={styles.grid}>{skus}</ul>
                </div>
                <FormNextButton
                  pageName={"container"}
                  disabled={false}
                  option
                />
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
};

export default ProductPage;
