import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../../styles/Form.module.css";

const DesignClientPage: NextPage = () => {
  const [location, setLocation] = useState<string>("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Find your perfect setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Become a design client</h1>
        <div>
          <button type="button">Contact us</button>
        </div>
      </main>
    </div>
  );
};

export default DesignClientPage;
