import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import FormNextButton from "../../components/form/next-button";
import { useAppContext } from "../../context/context-provider";
import styles from "../../styles/Form.module.css";

const LocationPage: NextPage = () => {
  const [location, setLocation] = useState<string>("");
  const [context, setContext] = useAppContext();
  const currentRouteIndex = context.routes.indexOf("location");

  console.log(context.routes);
  useEffect(() => {
    if (location.length > 0) {
      context.addRoute("business-types");
      setContext(context);
    }
  }, [location]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Find your perfect setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>What location are you in</h1>
        <div>
          <input
            className={styles.input}
            type="text"
            value={location}
            onChange={(e) => setLocation(e.target.value)}
            required
          />
        </div>
      </main>
      <FormNextButton pageName={"location"} disabled={location.length < 1} />
    </div>
  );
};

export default LocationPage;
