import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Confetti from "react-confetti";
import { FormCart } from "../../context/form-context";
import styles from "../../styles/Form.module.css";
import { addToFirebase } from "../../utils/form/firebase";

const Summary: NextPage = () => {
  const [cart, setCart] = useState<FormCart>({});

  useEffect(() => {
    console.log("use");
    // Retrieve from local storage
    const cart: string | null = localStorage.getItem("cart");
    const locaitons: string | null = localStorage.getItem("locations");
    const shippingInfo: string | null = localStorage.getItem("shipping");
    // Send to Firebase
    if (cart != null && locaitons != null && shippingInfo != null) {
      addToFirebase(
        JSON.parse(cart),
        JSON.parse(locaitons),
        JSON.parse(shippingInfo)
      );
      console.log("Adding");
      localStorage.clear();
      setCart(JSON.parse(cart));
    }
  }, []);

  let items = [];
  for (let city in cart) {
    items.push(<div>{city}</div>);
    items.push(
      cart[city].map((sku) => (
        <li style={{ display: "inline" }} key={sku.title}>
          <div className={styles.summaryRow}>
            <Image
              src={sku.image}
              height={100}
              width={125}
              alt={"takeout front"}
            />
            <div className={styles.summaryText}>{sku.title}</div>
            <div>{"x" + sku.quantity}</div>
          </div>
        </li>
      ))
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Find your perfect setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Confetti width={1800} height={1200} />
        <h1 className={styles.title}>Congrats on your purchase!</h1>
        <div>{items}</div>
      </main>
    </div>
  );
};

export default Summary;
