import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Confetti from "react-confetti";
import { FormCart } from "../../context/form-context";
import { addToFirebase } from "../../utils/form/firebase";

const Summary: NextPage = () => {
  const [cart, setCart] = useState<FormCart>({});

  useEffect(() => {
    console.log("use");
    // Retrieve from local storage
    const cart: string | null = localStorage.getItem("cart");
    const locaitons: string | null = localStorage.getItem("locations");
    const shippingInfo: string | null = localStorage.getItem("shipping");
    // Send to Firebase
    if (cart != null && locaitons != null && shippingInfo != null) {
      addToFirebase(
        JSON.parse(cart),
        JSON.parse(locaitons),
        JSON.parse(shippingInfo)
      );
      console.log("Adding");
      // localStorage.clear();
      setCart(JSON.parse(cart));
    }
  }, []);

  let items = [];
  console.log(cart);
  for (let city in cart) {
    items.push(
      <div>
        <div>{`${city} orders`}</div>
      </div>
    );
    items.push(
      cart[city].map((sku) => (
        <div
          className="flex columns-2 justify-between items-center mr-4 my-4"
          key={sku.title}
        >
          <div className="flex columns-2 justify-start items-center">
            <div className="h-16 w-16 overflow-hidden rounded place-content-center mr-3">
              <Image
                src={sku.image}
                alt={"takeout front"}
                height={"100%"}
                width={"100%"}
              />
            </div>
            <div>
              <div className="text-md font-semibold mb-0.5">{sku.title}</div>
              <div className="text-sm text-gray-300">{`Qty ${sku.quantity}`}</div>
            </div>
          </div>
        </div>
      ))
    );
    items.push(<div className="h-8" />);
  }

  return (
    <div className="w-screen h-screen bg-black flex overflow-hidden">
      <Head>
        <title>Find your perfect setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col container mx-auto items-center py-4 text-white">
        <Confetti width={1800} height={1200} />
        <h1 className="text-5xl font-theinhardt text-white text-center">
          Congrats on your purchase!
        </h1>
        <div className=" mt-16 border-2 rounded-xl px-8 pt-8">{items}</div>
      </main>
    </div>
  );
};

export default Summary;
