import { loadStripe } from "@stripe/stripe-js";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import ProgressBar from "../../components/form/progress-bar";
import { useAppContext } from "../../context/context-provider";
import styles from "../../styles/Form.module.css";

const stripePromise = loadStripe(
  process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY ?? ""
);

const Summary: NextPage = () => {
  const [eol, checkEol] = useState<boolean>(false);
  const [numChanges, cartChanged] = useState<number>(0);
  const [context, updateAppContext] = useAppContext();
  const router = useRouter();

  const { canceled, cart } = router.query;
  console.log(context.cart);

  // useEffect(() => {
  //   if (cart) {
  //     const cartArr = cart.toString().split(",");
  //     console.log(cartArr);
  //     context.cart = {};
  //     cartArr.map((i) => {
  //       const item = i.split("^");
  //       [swapboxProduct, swapcupProduct].map((p) => {
  //         const skuIndex = p.getSkuFromTitle(item[0]);
  //         if (skuIndex != "0") {
  //           let sku = p.sku.get(skuIndex)!;
  //           sku.quantity = item[1];
  //           context.addToCart(sku, "");
  //         }
  //       });
  //     });
  //     updateAppContext(context);
  //     cartChanged((prev) => prev + 1);
  //   }
  // }, [cart, numChanges, updateAppContext, context]);

  useEffect(() => {
    // Check to see if this is a redirect back from Checkout
    const query = new URLSearchParams(window.location.search);
    if (query.get("success")) {
      console.log("Order placed! You will receive an email confirmation.");
    }

    if (query.get("canceled")) {
      console.log(
        "Order canceled -- continue to shop around and checkout when you’re ready."
      );
    }
  }, []);

  let items = [];
  for (let city in context.cart) {
    if (context.locations.length > 1) {
      items.push(<div>{city}</div>);
    }
    items.push(
      context.cart[city].map((sku) => (
        <li style={{ display: "inline" }} key={sku.title}>
          <div className={styles.summaryRow}>
            <Image
              src={sku.image}
              height={100}
              width={125}
              alt={"takeout front"}
            />
            <div className={styles.summaryText}>{sku.title}</div>
            <div>{"x" + sku.quantity}</div>
          </div>
        </li>
      ))
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Find your perfect setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProgressBar pageName="summary" />
      <main className={styles.main}>
        <h1 className={styles.title}>Your perfect setup</h1>
        <div>
          <ul>{items}</ul>
        </div>
        <div>
          <input
            type="checkbox"
            id="eol"
            checked={eol}
            onChange={(e) => checkEol(!eol)}
          />
          <label htmlFor="eol">Agree to EOL policy</label>
        </div>
        <div style={{ marginTop: "20px" }}>
          {/* <form action="/api/checkout" method="POST"> */}
          <Link href={"checkout"}>
            <button className={styles.checkoutButton} type="submit" role="link">
              {`Checkout: \$${context.calculateCost()}`}
            </button>
          </Link>
          {/* </form> */}
        </div>
        {canceled && (
          <div className={styles.payErrorText}>
            Something went wrong, please try again
          </div>
        )}
      </main>
    </div>
  );
};

export default Summary;
