import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import ProductPage from "../../components/form/product-page";
import { swapcupProduct } from "../../constants/form";
import styles from "../../styles/Form.module.css";

const Swapcup: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Find your perfect setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductPage product={swapcupProduct} />
    </div>
  );
};

export default Swapcup;
