import type { NextPage } from "next";
import { getCsrfToken, useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";

const DashboardLogin: NextPage = () => {
  const [company, setCompany] = useState<string>("");
  const [firstName, setFirstName] = useState<string>("");
  const [lastName, setLastName] = useState<string>("");
  const [email, setEmail] = useState<string>("");
  const { data: session, status } = useSession();

  async function handleLogin() {
    const csrfToken = await getCsrfToken();
    fetch("/api/auth/create/createUser", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        csrfToken: csrfToken,
        email: email,
        firstName: firstName,
        lastName: lastName,
        companyName: company,
      }),
    })
      .then((res) => console.log(res))
      .catch((e) => console.log(e));
  }

  return (
    <div className="w-screen h-screen bg-black flex overflow-hidden">
      <Head>
        <title>Find your perfect setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col container mx-auto my-auto items-center py-4 text-white">
        <h1>{status === "authenticated" ? "Logged In" : "Not Logged In"}</h1>
        <input
          name={"Email"}
          className="p-1 border-2 text-lg w-full bg-stripe-gray border-gray-500 outline-re-green-800 rounded mb-4"
          type="text"
          value={email}
          placeholder={"Email"}
          onChange={(e) => setEmail(e.target.value)}
        />
        <input
          name={"First Name"}
          className="p-1 border-2 text-lg w-full bg-stripe-gray border-gray-500 outline-re-green-800 rounded mb-4"
          type="text"
          value={firstName}
          placeholder={"First Name"}
          onChange={(e) => setFirstName(e.target.value)}
        />
        <input
          name={"Last Name"}
          className="p-1 border-2 text-lg w-full bg-stripe-gray border-gray-500 outline-re-green-800 rounded mb-4"
          type="text"
          value={lastName}
          placeholder={"Last Name"}
          onChange={(e) => setLastName(e.target.value)}
        />
        <input
          name={"Company"}
          className="p-1 border-2 text-lg w-full bg-stripe-gray border-gray-500 outline-re-green-800 rounded mb-4"
          type="text"
          value={company}
          placeholder={"Company"}
          onChange={(e) => setCompany(e.target.value)}
        />
        <button className=" px-2 py-4 bg-re-green-500" onClick={handleLogin}>
          Create User
        </button>
      </main>
    </div>
  );
};

export default DashboardLogin;
